:PROPERTIES:
:ID:       4B5622FD-8CEC-479B-BF2E-C72685007368
:END:
#+title: A Manifesto for Destabilisation

* Intro

I wanted to share my thoughts as a manifesto in the form of one that
might be created by an artistic movement - the manifesto for agile
software development is most certainly not an inspiration in its now
tired and insepid form. I want to talk in symbolism and in the extreme
to express some of my thoughts about organisational homeostasis and
what a movement to address this challenge might look like. There are
some shady figures whose influence is felt through this. I cannot deny
their influence, despite some of their offensive views.

* The Manifesto for Organisational Destabilisation

Up on the crest of the world, once more we hurl our challenge to the stars!

Marinetti - The Futurist Manifesto

** The Stagnation

The thick mud around us - stagnant and reference 1st world war poetry.
Four hundred thousand soldiers slain, were drowned within unholy mud. Corpses of the no
w redundant gave their best and got their worst.
I try and dream of fields of green,
from my prairie childhood.
But it doesn't come so easy,
midst these fields of mud and blood.
Themes of mud and fire
Time stood still
Trapped
On a bungee cord
Stuck in a present that doesn't exist
The objects around make no sense, doubt their reality
Introduce the concepts to appear later in shadowy forms
The shadows of ...
Echos of the vision  below
Fear of decomposition and collapse - avoiding the blood and fire.
The need and desire for balance.
Propping up
Dali - Persistence of Memory and soft time
Dali - Sleep
Homeostasis
Thick Mud
Walls
Crisis creates the right behaviour - the change is nascent within us. Covid 
was a crisis that like our immune system failing. Destablised the organism
and change emerged.
Immune system is fighting back excessively
visions induced by epilepsy
Throught the fog of ambuigity to the clarity of paradox


** The Vision

I see Marinetti standing on the crest of the world, cloaked in fire
and blood. Both repulsive and compelling. I cannot see whether the
blood is the life that flows within him and his writing or the blood
of the innocent that his worship of war let flow in the decades
following his works of art and violence. Fire surrounds him, consuming
and releasing energy, destroying and creating. His words burnt through
the 20th century, ravaging the world and glorifying the ignoble,
id-noble destroyers of humanity.

His words echo across planes of thick stagnant mud, where bodies gasp
for air: "I will this, it is what you must throw, in indigantaion,
towards the stars!" His words echo forward through a time stretching
and contracting from the now (some kind of symbolism here about the
influence of history and immanence).



Marinetti destroyed by something in this!


Surrealist Manifesto
Futurists Manifesto

Thresholds
Marinetti
Windows - I see a dog, you see a cat
Frames
Constraints
Movement and difference and loss of identity
Idealism
Transcendence
Kant/Descartes/Bergson/Deleuaze/Nietzsche - as a donkey
Surrealism

** To action destabilisationists!

Our large organisations have become stagnant and are drowning within
unholy mud. We fight the flow of our lifeblood from us at great
expense, the fire destroys and creates. The corporate immune systems
have taken over and promise stability in a past world that changes
little. Our immune system prevents the now needed adaptation and while
promising resilience offers us brittle robustness that we need to
fight in order to get real change. Our philosophical and
organisational legacy offers us a shared frame to make sense of the
world, but it is a trap that we must furiously fight to escape. And
fight it we can if we look to destabilise and fight the homeostasis
that like thick mud drowns us and leaves us gasping for air on its
surface.

Steer into the fog and dive into the chaos. Destabilise and let the new
and novel emerge. See our organisations reborn.

We
We believe
We believe in:

- Destabilisation of the western philosophical influence trapping us
  in thinking about reality in limiting and binary manners.
- Thinking of our complex world through an ontology of relationships
  over an ontology of identity.
- Avoiding the trap of the transcendence believing what we need to be
  exists as something other.
- Recognising that the future exists in the present.
- Destabilising our shared frames of sensemaking.
- The power of the metaphor to both hide and reveal.
- The power of language as action over representation.
- Destabilising the homeostasis.
- Fighting our over active immune systems.
- The discovery of paradox as the starting point for change.
- The power of physical and abstract thresholds as points of
  transition where change is lost and won.
- Ambiguity and de-categorisation.
  
The destabilisationists
