#+TITLE: Assemblage Theory

* References

- [1] Todd May, Gilles Deleuze - An Introduction, 2005, Cambridge
University Press
- [2] Manuel Delanda, A New Philosophy of Society,
2006, Continuum
- [3] Manuel Delanda, Assemblage Theory, 2016, Edinburgh
University Press
- [4] Differential Ontology, Internet Encyclopedia of Philosophy.

* Todd May on Deleuze

[1 p29] *Transcendence* (of Forms, God, human subject,
material/mental) requires the existence of two ontological
substances. It requires that one substance is superior to
another. Superior in power and value. The transcending power brings
the transcended world into full flower, liberating it from the prison
of its incapacities. Transcendence does not corrupt; it completes.

[1 p38] *Expression* (attributes/modes/substance) Origami is the
folding of paper into different recognisable figures... there is no
cutting of paper. No outside elements are introduced into
it. Everything happens as an expression of that particular bit of
paper. It is only the paper that is folded and unfolded into new
arrangements, these arrangements being the *modes* of the paper which
is the oragami's substance. The extension of the paper would be its
*attribute*. If we can imagine the paper's being able to fold and
unfold itself, we come close to the concept of expression. Further, we
must see each figure as part of the process, not a finished product,
if we are to grasp the concept of *substance* (Folding, unfolding,
refolding) /ref - affordances?/

[1 p55] (Bergson) Duration is a virtual multiplicity, a realm of
difference where differences are not between previously constituted
identities but where difference "differs with itself" ... It is from
the realm of differences that the present arises, as it's virtuality
actualizes into specific spacial features. Thus, "the Bergsonian
revolutions is clear: We do not move from the present to the past,
from perception to recollection, but from the past to the present,
from recollection to perception." (!! /differential ontology notes?/

[cont] The immanence of duration to the present has an important
consequence: the present always has a greater potential for
transformation than it appears to have.

[1 p64] [Nietzsce] The dice are thrown. This is the eternal return. The
dice are always thrown, at every instant. The future is always with
us, here and now, just as the past is (/actulized in the present/). A
pair of dice, loaded with the multiplicity that is duration is
thrown. The dice fall back, they show a combination. There you have
it. Those are the numbers. That is your throw. You may get another,
but it will not erase the combination taht faces you, That combination
will always have happened, and will always be part of your score. The
past is always part of every present.

[1 p68] (more?) To afirm the eternal return is to recognise a world of
virtual difference that lies beyond the particularities of our
present, to set free the active forces of creativity, to refuse to
separate those forices from what they can do. It is to recognize that
the future does not offer us guarantees of what will be there, and
moreover that to seek guarantees is to restrict our capacities, to
imprison our bodies, to stifle our creative possibilities, to betray
what may be the best in us for the fear that it may instead be the
worst.

[1 p72] *QOUTE* If we abandon this [our current] way of thinking of
our world, then alternative ways of living may appear to us. If things
don't have strict borders of identity and if the relations among them
are not reducible to natural laws, then we can no longer be sure of
what a body is capable. Perhaps there is more going on in our world
that is presented to us. We don't know. The only way to find out is to
experiment.

[1 p83] "We are led to believe that problems are given ready-made, and
that they disappear in the responses or the solution....We are led to
believe that the activity of thinking...begins only with the search
for solutions."

[cont] Instead of seeing these as problems that seek a particular
solution, we might see them as opening up fields of discussion, in
which there are many possible solutions, each of which captures
something, but not everything, put before us by the problem.

[1 p85] For Deleuze, this is a case of the solution defining the
problem. To see why, recall the relation of the virtual to the
actual. The virtual is not the same as the actual; it has a different
character. Solutions are actual; problems are virtual. The dodo bird
is an actual solution to the problem of a particular
environment. Solutions present themselves as stable identities whereas
problems present themselves as "open fields" or "gaps" or "ontological
folds." Problems are inexhaustable, while solutions are a particular
form of exhuastion.  For the *dogmatic image of thought*, being is
defined in terms of actuality, rather than virtuality. It is a matter
of stable identities rather than difference. To think ontologically in
terms of stable identities is to read solutions back into problems, to
approach problems in terms of solutions. For Deleuze, being is not a
matter of stable identities that representational thought gives
us. Identities come later, as particular solutions to the problems
that being places before us, the problem that being is. To confuse
those *identities with being* is to confuse the actual with the
virtual. It is to confuse solutions and problems. The dogmatic image
of thought gives primacy to identities, to the actual and
solutions.

[1 p86] In Deleuze's hands, ontology is not a matter of telling us
what there is but of taking us on strange adventures, bringing us far
afield of ourselves.

[1 p90] Bergson's concept of duration offers the framework for
understanding the process of the unfolding of difference as the
actualization of the virtual. Spinoza's concept of the univocity of
being reveals this process as an immanent unfolding, an expression,
rather than a transcendent creation or emanation.

[1 p98] (/denotation, manifestation, signification/) Denotation is the
relation of the proposition to external affairs...Manifestation
concerns the relation of the proposition to the person who speaks and
expresses himself....Where denotation points "forward" toward the
world the propostion speaks of, manifestation points "backwards"
toward the proposition's origin, toward the one who utters the
proposition. With [these] we have three intersecting elements in
language: a proposition, a speaker, and a state of affairs. Together
they form a representational world of language. But id we stop [here]
we will miss much of what goes on both within language itself and in
the relation of language to the speaker and world. We need a third
concept: signification. Signification has to do with the implications
of propositions, with what follows form a proposition or a group of
propositions. (/sylogism/)

[1 p102] Isn't Deleuze saying something simple here? Isn't he saying
that when we use the word "green" we make the world appear a certain
way for the people who hear us? When I say "the leaf is green" aren't
I just ascribing a quality to something in the world, manifesting
myself in words that denote the world? ...It occurs in the
representational order of things. But he insists that something else
occurs as well, something that eludes that representational order but
is just as real as that order....To green, to be a stickup, is to
orient bodies in certain ways, to create new lines of engagement among
things, to cut a trajectory through the world, a trajectory in which
both oneself and the world are affected. It is not a matter of
representation but of an event that occurs within and through
language, at its point of intersection with the world. (/see Wieck/)

[1 p106] Language is a system of differences. It exists not as a
system of positive elements, each which has its indentity. Rather is
is defined by differences that, like the difference of being, can be
palpated but not brough under represenational categories. To speak
then, is to bring two series of differences into contact: being and
language.

[cont] For Deleuze, this contact between two series of differences
implies the existence of certain kinds of paradoxical elements that
belong to both and neither series at the same time... This paradoxical
element that both is and is not of lnaguage and is and is not of the
world, is nonsense.

[cont] The name of the song is called 'Haddocks' Eyes'."  "Oh, that's the
name of the song, is it?" Alice said, trying to feel interested.  "No,
you don't understand," the Knight said, looking a little vexed.
"That's what the name is called. The name really is 'The Aged Aged
Man'."  "Then I ought to have said 'That's what the song is called'?"
Alice corrected herself.  "No, you oughtn't: that's quite another
thing! The song is called 'Ways And Means': but that's only what it's
called, you know!"  "Well, what is the song, then?" said Alice, who
was by this time completely bewildered.  "I was coming to that," the
Knight said. "The song really is 'A-sitting On A Gate': and the tune's
my own invention." 

[cont] This proliferation is not, for Deleuze, merely a game that can
be played at the margins of language. It points to something essential
about language itself. It is nonsense that allows language and the
world to come together.... Without this paradox, there would only be
the non-communication of these two series, a silence between them.

---
[4]

Differential ontology understands ththe identity of any given thing as
constituted on the basis of the ver-changing nexus of relations in
which it is found. Therefore identity is a secondary determination,
while difference, or the constituitive relations that make up
identities, is primary.

Time - puncti-linear, a whole series of 'now' points. Husserl - time
is not experienced as a series of discrete, independent moments, but
is always thick with past and future. (phenomenology)

[4]
---

[1 p111] Swimmers do not learn facts about the water and about their
bodies and then apply them to the case in hand. The water and their
bodies are swarms of differences. In order to navigate their bodies
through the water, they will need to acquire a skill: to "conjugate"
their bodies with the water in such a way as to stay on it's surface.

[1 p125] Machines do not operate out of lack. They do not seek to
fulfill needs. Instead they produce connections. Moreover, the
connections they produce are not pre-given; machines are not
mechanisms. Machines are productive in unpredictable and often novel
ways. The concept of a machine as Deleuze and Guattari employ it is
like the concept of difference...They are not reducible to any one set
of connections, any particular identity. Even when they are connected
in a particular way they are capable of other connections and other
functions.

[cont] There is a virtuality to machines that inheres in any set of
actual connections and that allows them to connect in other and often
novel ways.

---

[2 p1] New approach to social ontology that does not undermine social
realism. Opposed to social constructivism. Social entities treated as
assemblages that cut across the nature-culture divide.

[2 p4] Unlike organic totalities, the parts of an assemblage do not
form a seamless whole. Assmeblage theory avoids an ontological
commitment to essences.

[2 p8] The organismic metaphor involves making a superficial analogy
between society and the human body, and to postulate that just as
bodily organs work together for the organism as a whole, so the
function of social institution is to work for the in harmony for the
benefit of society. This is associated with the functional school of
sociology. The basic concept being /relations of interiority/: the
component parts are constituted by the very relations they have to
other parts in the whole. A part detached from such a whole ceases to
be what it is, since being this particular part is one of its
constituitive properties.

[3 p2] (too spatial) A better choice would be intinsic and extrinsic,
but the intent is clear: if a relation constitutes the very identity
of what it relates it cannot respect the heterogneity of the
components, but rather it tends to fuse them together into a
homogonous whole.

[3 p21] Downward causality - Wholes emerge bottom up, depending
causally on their components, but have a top down influence. This d-c
is needed to account fo the fact that most assemblages are composed of
parts that come into existence after the whole has emerged.

[3 p27] Ritual as coded habit?

[3 p29] Any event that takes attention away from the subject of
conversation to focus it elsewhere can destablise this assemblage.

[2 p10] The main alternative to this is assemblages: wholes
characterized by relations of exteriority. A component part can be
'unplugged' and 'plugged' into a different assemblage in which its
interactions are different. [NOTE: affordances]

[2 p11] The properties of a whole cannot be reduced to those of its
parts - they don't result from an aggregation of the component's own
properties but of the actual exercise of their capacities. These
capacities do depend on a components properties but cannot be reduced
to them since they involve reference to the properties of interacting
entities. Metaphor of symbiosis between the wasp and orchid -
contingently obligatory relations that cannot be investigated by
thought alone. Ecosystems as assemblages, but not the species
themselves.

[2 p12] Assemblage is defined along two dimensions: One dimension
describes the variable roles the components play from material to
expressive. The other dimension defines the processes that the
components are involved with that stabilise or destabilse the identity
of the assemblage, increasing its degree of internal homogeneity or
the degree of sharpness of it's boundaries - territorialisation and
deterritorialisation.

[2 p15] coding provides further stabilisation. Many social assemblages
are not highly coded or highly territorialised. The more formal and
rigid the rules, the more socail encounters may be said to be coded.

[2 p28] Taxanomic essentialism - reified generalities. But there is no
need to be ontologically committed to the existence of hydrogen in
general but only to the objective reality of large populations of
hydrogen atoms.

[2 p29] A body-plan defines a space of possibilities with topological
structure. The notion of this structure is crucial in assemblage
theory. The set of possible capacities of an assemblage is not
amorphous since different assemblages displa different sets of
capacities. Phase spaces in physics and chemistry - structure is given
by topological invariants - attractors, and dimensions that represent
degrees of freedom - ways of changing. Social sciences - a more
complex distribution of topological invariants
(attractors). Distributions of these may replace Aristotle's genera.

[3 p120] Attractors and their basins define zones of stability, since
they pin down trajectories to a smal set of states and do not let them
escape.

[2 p35] Low density networks with more numerous weak links , are for
this reason capable of providing their component members with novel
information about fleeting opportunities.

[2 p40] Biological species are not general categories of which
organisms are members, but larger scale individual entities of which
organisms are component parts.

[2 p45] General categories do not refer to anything in the real world
and to believe that they do leads directly to essentialism.

[2 p50] The main territorialising process providing the assemblage
with a stable identity is habitual repetition. It follows that any
process which takes the subject back to the state it had prior to the
creation of fixed associations between ideas can destabilise personal
identity.

[2 p53] A good example of threats to ritual stability are embarrasing
events, such as linguistic errors.

[2 p66] Stories and categories are real group boundaries not
phenomonologically experienced borders and play a boundary defining
role.

[2 p74] Any process that calls into question the extent of legitimate
authority, such as a clash between organisations with overlapping
jurisdictions, can destablise their boundaries.

[2 p81] Networks of interdependent firms can be considered highly
territorialised.

[2 p83] The faster the rate of innovation, the more a given network
will benefit from the collective learning process of the small form
extreme and the more inadequate the self-sufficient approach of an
oligopoly of large firms will become.

[2 p85] *reified generalities are not legititmate ontological*
*entities*

[2 p118] Every social entity is shown to emerge from the interactions
among entities operating at a smaller scale.

---

[1 p133] "How might we go about living?"... Seen from Deleuze and
Guattari's viewpoint, the question might become something like this:
"What connections might we form?" Or, "What actualizations can we
experiment with."... we need to bear in mind that the "we" of the
questions is not a given we. It can be a group. It can be an
individual. It can be an ecosystem or a pre-individual part or a
cross-section within an environment or a geographical slice. What
makes it a "we" is not the stability of identity. It is the
participation in the formation of connections.

[1 p156] There is another better way to describe what Coltrane was
doing. It starts with the music. Music is a virtual field of
differences that can be actualized in many different ways... He did
not so much compose or arrange or express; he searched. He thre the
dice... He investigate to see what else the music might contain that
it had not shown before. He played not to display the actual but to
touch the virtual.

[1 p165] Cities are not organic and they are not mechanistic. They are
machinic. It is not that no order emerges. An order, an actualisation,
does emerge. But its emergence has nothing to do with self subsistent
elements arranged according to a pre-given pattern or from connections
that are melded once and for all. It emerges from specific contextx of
diversity in ways that both create and are created by the elements of
that diversity.

[1 p169] We are taught what is to be thought of as erotic, what we
should be aroused by... But it often does not happen like that. It is
often that something else becomes erotic. The eye is caught by the
glint of light from a knee. The roughness of a patch of skin becomes
provocative to a finger... A lisp or stutter arouses. One part of a
body calls out to another, not with information but with
invitation. Or better, a relationship of eroticism occurs between them
that creates both subjects and objects. There is an event, an event of
erotics that arises across and between the surfaces of bodies. It may
be a surprise to us to discover these sensations, these arousals. But
that is because we still do not know of what a body is capable.
