:PROPERTIES:
:ID:       089677E5-0635-4437-B71F-BECE3A52C551
:END:
#+TITLE: Notes on: Axelrod, R. (2008): Harnessing Complexity

[p16] A system should be called complex when it is hard to predict not
because it is random but because the regularities it does have cannot
be briefly described.  Murray Gell-Mann
 What is the right balance between variety and uniformity?
 What should interact with what, and when?
 Which agent or strategies should be copied and which should be destroyed?

[p22] Central questions:

[p26] If complexity is rooted in patterns of interaction among agents, then we might expect systems to exhibit increasingly complex dynamics when changes occur that intensify interaction among their elements.

Variation

[p39] Copying with error (genetic mutation) inkjet principle was
discovered when a research laboratory syringe malfunctioned. There are
many other processes that introduce noise into operations of copying
or re-creation, thereby producing variants that are sometimes highly
novel.

[p42] Recombining mechanisms - Constraint relaxation seeks solutions
to a problem by generating variants that violate some of the
situation's constraints.

[p43] Exploration vs exploitation trade-off - This principle captures
the tension in CAS between creation of untested types that may be
superior to what currently exists versus the copying of tested types
that have so far proven best.

[p43] Eternal boiling - potentially valuable structures are broken
apart before they can effectively put to use.  [p44] Premature
convergence - very speedy imitation of an initial success cuts of
future systems improvements.  • Problems that are long term and
widespread • Problems that provide fast, reliable feedback • Problems
with low risk of catastrophe form exploration • Problems that have
looming disaster

[p50] Exploration (encouragement of variety) is especially valuable
when: Interactions

[p75] A change that increases proximity, that makes two agent more
likely to interact, means that on average the interaction will occur
sooner. If it takes place before events that it would otherwise have
followed, it may change the character or likelihood of those
events. The system can have an entirely different history as a result.

[p78] The essential effect of a barrier to movement is to make some
agents more proximate - more likely to interact with each other - and
others less.

[p85] A manager... has the opportunity to manipulate the role of time
more directly.  Agent following

[p88] The ability to acquire interaction patterns implicitly without
having a good theory of how things work.

[p88] Most of the accomplishments of biological evolution, and much
human social change, have occurred without the benefit of such
explicit knowledge, let alone theoretical understanding.

[p90] There are also disadvantages to the social structures that
accumulate through pervasive agent following. It can result in loss of
informational diversity...  and premature convergence.

[p91] It can be shown that a modest proportion of ties to distant
others suffices to "shrink the social world" dramatically. (Watts &
Strogatz, 1998)

[p92] Paradox - as individual agents experience more diverse contacts,
the system can become less diverse... This is not the most favourable
situation for adaptation... premature convergence. The ideal breeding
ground for novel lifeforms seems to be an archipelago or a network of
mountain valleys.  Improvements occur but spread slowly to avoid a too
rapid loss of diversity.

[p96] Those who experiment with co-operative actions do badly, because
they meet unresponsive agents. With these co-evolutionary dynamics,
selfish strategies spread through the population, becoming endemic.

[p106] You cannot know whether small events are relieving or
increasing the stress. "In the critical state, the sand pile is the
functional unit. not the grain of sand" (Bak 1996) Bak introduces the
idea of self-organised criticality, the tendency of the system to stay
near its critical state.

[p112] If security is to be achieved through redundancy, it can help
to have redundant systems be as different as possible (rather than
exact copies of each other) so that some system might be able to
resist an attack that is fatal to the others.

[p113] The way routines form is important for organisations. The
easier it is to create good ones and modify bad ones, the more
productive organisations can be.  Selection

[p122] When members of an organisation assess a situation from
different evaluative angles, they generate a greater variety of new
possibilities that, if not excessive, can have greater value to the
organisation.

[p122] How success is defined affects the chances of effective
learning. The central problem with victory as the sole measure of
success is that it only comes once in a game and at the end.

[p122] In a seeming paradox, you increase the chance of winning by
concentrating on a set of criteria that does not include winning.

[p125] From the point of view of harnessing complexity, a major
advantage of prize competitions is that they can award credit to
people or activities based on criteria that are different from current
standards.  Books Page 2 criteria that are different from current
standards.

[p129] Selection pressure - The trade-off between strong and weak
selection pressure raises the familiar issues of choosing between the
balance between exploiting the best current outcomes and using variety
to explore for future possibilities.

[p130] In the short run, selection pressure converts existing variety
to new exploitation, but in the long run exploration may suffer.

[p136] Since CAS are inherently difficult to understand or predict, it
follows that attribution of credit in selection will often be
difficult and prone to mistakes.

[p148] What a leader does is especially likely to be copied by others.

Framework

[p154] Framework - Agents, or a variety of types, use their
strategies, in patterned interaction, with each other and with
artefacts. Performance measures on the resulting events drive the
selection of agents and/or strategies through processes of error prone
copying and recombination, thus changing the frequencies of types
within the system.

[p154] Use the framework to ask questions to help guide the user in
harnessing the complexity of the system.

[p155] Generate actions on variation, interaction & selection.
